// TODO: This is static and should be replaced when the Lumen's endpoints are available.
// All of these static variables are going to be moved to the Redux store and the components will listen to changes.
const releaseDate = '06/03/2022';


const sectionArray = [
  {name: 'Course Contents', items: ['About This Course.', 'Course Contents at a Glance.', 'Course Learning Outcomes.']},
  {name: 'Course Contents', items: ['About This Course.', 'Course Contents at a Glance.', 'Course Learning Outcomes.']},
  {name: 'Course Contents', items: ['About This Course.', 'Course Contents at a Glance.', 'Course Learning Outcomes.']},
];

export const COURSE_ARRAY = [
  {id: '1xxxxx', name: 'Abnormal Psychology', releaseDate: releaseDate, description: 'This comprehensive, ready-to-adopt Abnormal Psychology course provides thorough coverage of all topics from The Diagnostic and Statistical Manual of Mental Disorders, Fifth Edition (DSM-5), including a discussion of all major mental disorders, etiology, epidemiology, and treatments. The course includes frequent examples, case studies, videos, and practice opportunities to foster application and critical thinking.', sections: sectionArray},
  {id: '2xxxxx', name: 'Accounting for Managers', releaseDate: releaseDate, description: 'This comprehensive, ready-to-adopt Abnormal Psychology course provides thorough coverage of all topics from The Diagnostic and Statistical Manual of Mental Disorders, Fifth Edition (DSM-5), including a discussion of all major mental disorders, etiology, epidemiology, and treatments. The course includes frequent examples, case studies, videos, and practice opportunities to foster application and critical thinking.', sections: sectionArray},
  {id: '3xxxxx', name: 'Biology for Majors I', releaseDate: releaseDate, description: 'This comprehensive, ready-to-adopt Abnormal Psychology course provides thorough coverage of all topics from The Diagnostic and Statistical Manual of Mental Disorders, Fifth Edition (DSM-5), including a discussion of all major mental disorders, etiology, epidemiology, and treatments. The course includes frequent examples, case studies, videos, and practice opportunities to foster application and critical thinking.', sections: sectionArray},
  {id: '4xxxxx', name: 'Biology for Majors II', releaseDate: releaseDate, description: 'This comprehensive, ready-to-adopt Abnormal Psychology course provides thorough coverage of all topics from The Diagnostic and Statistical Manual of Mental Disorders, Fifth Edition (DSM-5), including a discussion of all major mental disorders, etiology, epidemiology, and treatments. The course includes frequent examples, case studies, videos, and practice opportunities to foster application and critical thinking.', sections: sectionArray},
  {id: '5xxxxx', name: 'Biology for Non-Majors I', releaseDate: releaseDate, description: 'This comprehensive, ready-to-adopt Abnormal Psychology course provides thorough coverage of all topics from The Diagnostic and Statistical Manual of Mental Disorders, Fifth Edition (DSM-5), including a discussion of all major mental disorders, etiology, epidemiology, and treatments. The course includes frequent examples, case studies, videos, and practice opportunities to foster application and critical thinking.', sections: []},
  {id: '6xxxxx', name: 'Biology for Non-Majors II', releaseDate: releaseDate, description: 'This comprehensive, ready-to-adopt Abnormal Psychology course provides thorough coverage of all topics from The Diagnostic and Statistical Manual of Mental Disorders, Fifth Edition (DSM-5), including a discussion of all major mental disorders, etiology, epidemiology, and treatments. The course includes frequent examples, case studies, videos, and practice opportunities to foster application and critical thinking.', sections: []},
  {id: '7xxxxx', name: 'Business Communication Skills for Managers', releaseDate: releaseDate, description: 'This comprehensive, ready-to-adopt Abnormal Psychology course provides thorough coverage of all topics from The Diagnostic and Statistical Manual of Mental Disorders, Fifth Edition (DSM-5), including a discussion of all major mental disorders, etiology, epidemiology, and treatments. The course includes frequent examples, case studies, videos, and practice opportunities to foster application and critical thinking.', sections: []},
  {id: '8xxxxx', name: 'College Success', releaseDate: releaseDate, description: 'This comprehensive, ready-to-adopt Abnormal Psychology course provides thorough coverage of all topics from The Diagnostic and Statistical Manual of Mental Disorders, Fifth Edition (DSM-5), including a discussion of all major mental disorders, etiology, epidemiology, and treatments. The course includes frequent examples, case studies, videos, and practice opportunities to foster application and critical thinking.', sections: []},
  {id: '9xxxxx', name: 'Computer Applications for Managers', releaseDate: releaseDate, description: 'This comprehensive, ready-to-adopt Abnormal Psychology course provides thorough coverage of all topics from The Diagnostic and Statistical Manual of Mental Disorders, Fifth Edition (DSM-5), including a discussion of all major mental disorders, etiology, epidemiology, and treatments. The course includes frequent examples, case studies, videos, and practice opportunities to foster application and critical thinking.', sections: []},
  {id: '10xxxxx', name: 'Concepts In Statistics', releaseDate: releaseDate, description: 'This comprehensive, ready-to-adopt Abnormal Psychology course provides thorough coverage of all topics from The Diagnostic and Statistical Manual of Mental Disorders, Fifth Edition (DSM-5), including a discussion of all major mental disorders, etiology, epidemiology, and treatments. The course includes frequent examples, case studies, videos, and practice opportunities to foster application and critical thinking.', sections: []},
  {id: '11xxxx', name: 'English Composition I', releaseDate: releaseDate, description: 'This comprehensive, ready-to-adopt Abnormal Psychology course provides thorough coverage of all topics from The Diagnostic and Statistical Manual of Mental Disorders, Fifth Edition (DSM-5), including a discussion of all major mental disorders, etiology, epidemiology, and treatments. The course includes frequent examples, case studies, videos, and practice opportunities to foster application and critical thinking.', sections: []},
  {id: '12xxxx', name: 'English Composition I Corequisite', releaseDate: releaseDate, sections: []},
  {id: '13xxxx', name: null, releaseDate: releaseDate, sections: []},
  {id: '14xxxx', name: null, releaseDate: null, sections: []}
];
